### ISSUE TITLE
Suggestion: Button to go to newer posts

### ISSUE THREAD

**Issue by vanitasvitae** [martinchodev/Diaspora-Native-WebApp#21]
There is this button at the bottom of the stream to go to older posts. I think it would be useful to have a button to go the other direction. 
For example if I went through the stream several times and then want to go one page "upwards" I cant do this at the moment. Instead I have to click the \* to go to the very first page and click the button at the bottom several times to go to the required page.

**Comment by mdev88** [comment]
Yes! I am aware of that problem and was thinking of releasing an update changing that soon.

What I will do is let the back button only for going back un the browsing history, then move the "exit app" option from the menu to the main title bar so that it's more visible, because with the new behaviour, you won't be able to exit the app with the back button anymore and you might feel like you are stuck inside the app :)

**Comment by mdev88** [comment]
Fixed in the lastest release.
