### ISSUE TITLE
Hide floating button when typing

### ISSUE THREAD

**Issue by jurf** [martinchodev/Diaspora-Native-WebApp#33]
Due to the size of the keyboard it covers the right quarter of the typing area.

**Comment by piraz** [comment]
The floating button looks great but it floats just over the confirmation buttons on my Galaxy S5.

With that I need to find a spot between the end of the page and the float button to click on the diaspora button and execute the action.

I was thinking in open an issue to make the button movable but hiding it will solve the problem too.

**Comment by mdev88** [comment]
The problem is that the floating button implemented is a third party library which has some limitations. I have made kind of a turnaround. It's not perfect, but it's better than having the button covering other parts of the screen that are oseful.
In the future, I will implement the oficial floating button and will probably have a better solution.
This changes will be up in the next update.
