### ISSUE TITLE
Add proxy/Tor support

### ISSUE THREAD

**Issue by sedrubal** [martinchodev/Diaspora-Native-WebApp#43]
I think Tor support would be great for countries where surveillance is a problem...

**Comment by mdev88** [comment]
This is a great feature. I am investigating and hope to implement it soon.

**Comment by teslasmoustache** [comment]
There's an app called Orwall which (I believe) allows you to force apps to use the Tor network. I'll check and make sure it actually works. If it does, I think this might be unnecessary.

EDIT: Nevermind. Turns out there are a few problems with Orwall on Lollipop involving IPTables. https://orwall.org/
https://github.com/EthACKdotOrg/orWall/issues/84

Therefore, an option within the app to route through Tor would be good.

**Comment by mdev88** [comment]
Yes I know Orwall, but it's a little too aggressive for my taste. I think having the ability to tunnel only this app via Tor would be useful.

**Comment by teslasmoustache** [comment]
agreed. I'm really liking this app, btw. Good work.

**Comment by vanitasvitae** [comment]
Orbot can transparently proxy any app through tor, but you need root for that.
A native feature would be great, indeed :+1:

**Comment by mdev88** [comment]
Working on it.
