### ISSUE TITLE
Remove exit button

### ISSUE THREAD

**Issue by sedrubal** [martinchodev/Diaspora-Native-WebApp#46]
Exit buttons are against the guidelines: http://blog.hatemalimam.com/exit-button-in-android-app/ and I don't think that there is use for it, is it?

**Comment by mdev88** [comment]
Closing the app with this option clears the cache, so that when you go back to the app a full reload of the page is foced. This is not the case if you change to another app or push the home button and come back (the cached version of tha page is shown, thus, you might have new notifications or posts in your stream and you wouldn't see them until you reload the page.
