### ISSUE TITLE
Add option to open current view in external browser

### ISSUE THREAD

**Issue by vanitasvitae** [martinchodev/Diaspora-Native-WebApp#52]
It would be nice to have a menu entry that opens the current stream page/post in a browser.
That can act as a workaround for #22 or #44 .

**Comment by mdev88** [comment]
Non diaspora links ARE open in an external browser.
I believe Images, at least in the mobile version of Diaspora don't have links pointing to the full image, so that's the first problem. I haven't figured out a way to for example capture the URL of the image on a long click or something like that.
As for showing user information, that's a low priority feature at the moment.

**Comment by vanitasvitae** [comment]
I think it would be enough, if there is a menu entry that starts an Intent with the current URL of the webview (that URL which is shown when the app has no Internet access)
