### ISSUE TITLE
The app is very, very slow, also problems with the standard (non-mobile) view

### ISSUE THREAD

**Issue by asereze** [martinchodev/Diaspora-Native-WebApp#8]
Hi,
I'm using the app in a LG E460 (Android 4.1.2) and it's very, very slow. A lot of times, also, clicking on things doesn't have any effect.

Also, if you switch to the "standard", PC view, there is not a search bar anymore.

**Comment by mdev88** [comment]
Hello
Can you tell me what are you comparing the speed of the app with? Other apps or a web browser? (which one?)
Can you specify what things you click that have no effect. Posting pictures for example is a known issue and will not work, but other links should work normally.

About the non-mobile version of the site, that is not a problem with the app, it's because that's how the mobile and non-mobile versions of Diaspora are made. Since this is a WebApp there's little I can do to fix that for the moment.

Thanks

**Comment by asereze** [comment]
Hi!
I'm comparing it with the other diaspora app in f-droid, but it seems to be sometimes slower than the web browser too.

Fist thing: the menu, sometimes (if it's already slowed down) It opens after a few seconds, or you have to click again.

![2015-07-05-18-54-50](https://cloud.githubusercontent.com/assets/11271324/8512545/eb8ef6b0-2347-11e5-975e-667fee811dbd.jpg)

Second: search. After searching for a tag, the app basically frozes (or allow you to come back to the stream) , the results are shown only if you wait for at least 6-7 seconds.
![2015-07-05-18-55-42](https://cloud.githubusercontent.com/assets/11271324/8512546/eb9c98d8-2347-11e5-87b6-d2feb5c75af1.jpg).

Third: showing comments/favourites (both in sfw and nsfw posts) and nsfw images. When you try to click, a lot of times nothing happens. You have to click dozens of times, and when it works it loads things only after a lot of seconds (like from 10 to 30, usually).

![2015-07-05-19-05-22](https://cloud.githubusercontent.com/assets/11271324/8512575/80225cc6-2349-11e5-84d3-9a6a018dca60.jpg)

Tanks to you, and sorry for my english!

**Comment by mdev88** [comment]
Thanks for all the feedback. I would be great if you could separate this problems in separate issues (no need to include all the images again, just the basic description) so I can tackle them one by one.

Thanks!

**Comment by asereze** [comment]
Ok, done!

**Comment by mdev88** [comment]
Created separate issues
